# Generated by Django 3.0.6 on 2020-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commentry', '0002_auto_20200617_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('matches', models.PositiveIntegerField()),
                ('win', models.PositiveIntegerField()),
                ('lost', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('net_run_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recent_matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200)),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1_over', models.PositiveIntegerField()),
                ('team2_over', models.PositiveIntegerField()),
                ('team1_score', models.PositiveIntegerField()),
                ('team2_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='top_scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('player_name', models.CharField(max_length=100)),
                ('games', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
