# Generated by Django 3.0.6 on 2020-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commentry', '0003_league_table_recent_matches_top_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='display_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_ad', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='game_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_place', models.CharField(max_length=100)),
                ('team1_img', models.ImageField(upload_to='images')),
                ('team2_img', models.ImageField(upload_to='images')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='homepage_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_team1', models.ImageField(upload_to='images')),
                ('image_team2', models.ImageField(upload_to='images')),
                ('name_team1', models.CharField(max_length=100)),
                ('name_team2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='team_squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_image', models.ImageField(upload_to='images')),
                ('player_name', models.CharField(max_length=100)),
                ('player_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='upcoming_matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('place_date', models.CharField(max_length=100)),
                ('team1_name', models.CharField(max_length=100)),
                ('team2_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recent_matches',
            name='team1_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recent_matches',
            name='team2_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league_table',
            name='net_run_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
