# Generated by Django 3.0.6 on 2020-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commentry', '0005_auto_20200628_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='musics')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioDataModel',
        ),
    ]
